[
"big",
# "fat",
# "broad shoulders",
# "built",
"curvy",
# "fit",
# "heavyset",
# "lean",
"long legs",
"tall",
# "long torso",
"long",
# "masculine",
"muscular",
"pear shaped",
"petite",
# "proportioned",
# "rectangular",
# "round apple",
# "short legs",
# "short torso",
# "short",
"skinny",
"small",
# "stocky",
# "sturdy",
# "attractive",
# "sexy",
]
