defaults:
  - renderer_kwargs: smplx

output_path: /home/nadav2/dev/data/CLIP2Shape/images/smpl_female_multiview # Path to save the images
gender: female
img_tag:
model_type: smpl
with_face: False
num_of_imgs: 3000
num_coeffs: 10
multiview: True
get_tall_data: False
# texture: /home/nadav2/dev/repos/CLIP2Shape/Flame/flame2020/mesh.png  # FLAME texture
# texture:  # SMAL texture (keep empty for random texture)

renderer_kwargs:
  py3d: True
  img_size: [1024, 1024]
  background_color: [0.0, 0.0, 0.0]
  # tex_path: /home/nadav2/dev/repos/CLIP2Shape/Flame/flame2020/mesh.png  # FLAME texture
  tex_path: /home/nadav2/dev/repos/Thesis/SMPLX/textures/smplx_texture_m_alb.png  # SMPLX texture