defaults:
  - renderer_kwargs: smplx

output_path: /home/nadav2/dev/data/CLIP2Shape/images/temp # Path to save the images
gender: neutral
img_tag:
model_type: smplx
with_face: False
num_of_imgs: 500
num_coeffs: 10
multiview: True
get_tall_data: False
# texture: /home/nadav2/dev/repos/CLIP2Shape/Flame/flame2020/mesh.png  # FLAME texture
# texture:  # SMAL texture (keep empty for random texture)

renderer_kwargs:
  py3d: True
  img_size: [1024, 1024]
  tex_path: /home/nadav2/dev/repos/CLIP2Shape/SMPLX/textures/smplx_texture_m_alb.png  # SMPLX texture
  background_color: [0.0, 0.0, 0.0]