output_path: /home/nadav2/dev/data/CLIP2Shape/images/smpl_male_multiview # Path to save the images
gender: male
img_tag:
model_type: smpl
with_face: True
num_of_imgs: 5000
num_coeffs: 10
sides: True
# texture: /home/nadav2/dev/repos/CLIP2Shape/Flame/flame2020/mesh.png  # FLAME texture
texture: #/home/nadav2/dev/repos/CLIP2Shape/SMPLX/textures/smplx_texture_m_alb.png  # SMPLX texture
# texture:  # SMAL texture (keep empty for random texture)

renderer:

  # ------ Pytorch3D ------
  name: pytorch3d
  kwargs:
    img_size: [512, 512]
    tex_path: ${texture}

    # # SMPLX cam params
    # dist: 2.5
    # elev: 15.0
    # azim: 0.0

    # SMPL cam params
    dist: 2.5
    elev: 10.0
    azim: 0.0

    # # FLAME shape cam params
    # dist: 0.8
    # elev: 0.0
    # azim: 0.0

    # # # FLAME expression cam params
    # dist: 0.5
    # elev: 0.0
    # azim: 0.0

    # # SMAL cam params
    # dist: 5.8
    # elev: 20.0
    # azim: -20.0

  # ------ Open3D ------
  # name: open3d
  # kwargs:
  #   for_image: True
  #   img_size: [512, 512]
  #   texture: ${texture}
  #   light_on: texture
