defaults:
    - renderer_kwargs: smplx

out_path: /home/nadav2/dev/data/CLIP2Shape/outs/performance_evaluation/smplx_male
model_path: /home/nadav2/dev/repos/Thesis/pre_production/smplx_male_new_algorithm.ckpt
min_value: 15.0
max_value: 30.0
effect_threshold: 0.5
color_map: YlOrRd

optimize_feature: betas
model_type: smplx

renderer_kwargs:
    img_size: [1024, 1024]
    tex_path:
    texture_optimization: True