defaults:
  - renderer_kwargs: smplx

model_type: smplx
optimize_features: betas
gender: male
img_out_size: [1024, 1024]
display: True
text:
  - fat
  # - tall
  # - muscular
  # - curvy
  # - pear shaped

renderer_kwargs:
  tex_path: /home/nadav2/dev/repos/CLIP2Shape/SMPLX/textures/smplx_texture_m_alb.png
  dist: 5.0
  img_size: [1024, 1024]