images_dir: /home/nadav2/dev/data/CLIP2Shape/outs/images_to_shape/smplx_shape/shapy_cherry_pick/shapy_results/raw_images
images_out_path: /home/nadav2/dev/data/CLIP2Shape/outs/images_to_shape/smplx_shape/shapy_cherry_pick/shapy_results/new_pose
rest_pose_path: /home/nadav2/dev/repos/Thesis/SMPLX/test.npy
verbose: False
display_images: False
collage: False
with_orig_image: False
save_orig_name: True
comparison_mode: False
comparison_data_path: #/home/nadav2/dev/repos/shapy/datasets/ssp_3d/labels/shapes.npy
save_obj: True
gender: female
suffix: jpg

# # FLAME - EXPRESSION
# with_face: True
# model_type: flame
# model_path: /home/nadav2/dev/repos/CLIP2Shape/production/flame_expression.ckpt
# texture: #/home/nadav2/dev/repos/CLIP2Shape/Flame/flame2020/mesh.png
# sliders_max_value: 30
# labels_weights: [0.5, 0.6, 0.8, 0.6]

# # FLAME - SHAPE
# with_face: False
# model_type: flame
# model_path: /home/nadav2/dev/repos/CLIP2Shape/production/flame_shape.ckpt
# texture: #/home/nadav2/dev/repos/CLIP2Shape/Flame/flame2020/mesh.png
# sliders_max_value: 30
# labels_weights: # [0.5, 0.6, 0.8, 0.6]

# SMPLX
with_face: False
model_type: smplx
model_path: /home/nadav2/dev/repos/CLIP2Shape/pre_production/smplx_female.ckpt
texture: #/home/nadav2/dev/repos/CLIP2Shape/SMPLX/textures/smplx_texture_m_alb.png
labels_weights: #[1.0, 0.8, 1.0, 1.2, 0.8]
# labels_weights: 

# # SMAL
# with_face: False
# model_type: smal
# model_path: /home/nadav2/dev/repos/CLIP2Shape/production/smal.ckpt
# texture:  # SMAL texture (keep empty for random texture)

renderer_kwargs:
    img_size: [450, 300]
    tex_path: ${texture}

    # SMPLX cam params
    dist: 2.2
    elev: 15.0
    azim: 10.0

    # FLAME shape cam params
    # dist: 0.8
    # elev: 0.0
    # azim: 0.0

    # # FLAME expression cam params
    # dist: 0.5
    # elev: 0.0
    # azim: 0.0

    # SMAL cam params
    # dist: 3.8
    # elev: 20.0
    # azim: 0.0