data_path: /home/nadav2/dev/data/CLIP2Shape/images
repo_path: /home/nadav2/dev/repos/CLIP2Shape
main_output_dir: /home/nadav2/dev/data/CLIP2Shape/outs/vertices_heatmap/optimizations/test

optimization_cfg:

  # # FLAME - Shape
  # texture: #${repo_path}/Flame/flame2020/mesh.png
  # model_type: flame
  # device: cuda
  # gender: neutral
  # text: 
  #   - "thin"
  #   - "big forhead"
  #   - "big eyes"
  #   - "big nose"
  #   - "big mouth"
  #   - "ears sticking-out"
  #   - "big eyebrows"
  #   - "thin lips"
  #   - "small chin"
  #   - "long neck"
  #   - "fat"
  #   - "chubby cheeks"
  #   - "long head"
  # total_steps: 50
  # optimize_features: shape_params
  # output_dir: ${main_output_dir}
  # dist: 0.8
  # elev: 0.0
  # azim: 0.0
  # lr: 0.1
  # # display: False

  # # FLAME - Expression
  # texture: #${repo_path}/Flame/flame2020/mesh.png
  # model_type: flame
  # device: cuda
  # gender: neutral
  # text: 
  #   - "happy"
  #   - "sad"
  #   - "worried"
  #   - "angry"
  #   - "surprised"
  #   - "disgusted"
  #   - "afraid"
  #   - "bored"
  #   - "open mouth"
  #   - "raise eyebrows"
  #   - "smile"
  #   - "frown"
  #   - "open eyes"
  # total_steps: 50
  # optimize_features: expression_params
  # output_dir: ${main_output_dir}
  # dist: 0.5
  # elev: 0.0
  # azim: 0.0
  # lr: 0.1
  # display: False

  # SMPLX
  texture: ${repo_path}/SMPLX/textures/smplx_texture_m_alb.png
  model_type: smplx
  gender: male
  device: cuda
  text: 
    # - "fat"
    # - "thin"
    # - "muscular"
    # - "short"
    # - "long legs"
    # - "narrow waist"
    # - "skinny"
    - "tall"
    # - "rectangular"
    # - "pear shaped"
    # - "average"
    # - "big"
    # - "curvy"
    # - "lean"
    # - "masculine"
    # - "proportioned"
    # - "stocky"
    # - "sexy"
    # - "sturdy"
    # - "broad shoulders"
    # - "fit"
    # - "round apple"
    # - "built"
    # - "heavyset"
    # - "petite"
    # - "small"

  total_steps: 100
  optimize_features: betas
  output_dir: ${main_output_dir}
  dist: 2.5
  elev: 15.0
  azim: 0.0
  lr: 0.1
  display: True

  # SMAL
  # texture:  # keep empty for random texture
  # model_type: smal
  # device: cuda
  # text: donkey
  # total_steps: 700
  # optimize_features: beta
  # output_dir: ${main_output_dir}
  # dist: 3.8
  # elev: 15.0
  # azim: 0.0
  # lr: 0.01