descriptors_dir: /home/nadav2/dev/data/CLIP2Shape/outs/vertices_heatmap/optimizations/smplx_multiview
corr_threshold: 0.7
model_type: smplx
gender: male
iou_threshold: 0.3
optimize_feature: betas
color_map: YlOrRd
color_threshold: 0.6


renderer_kwargs:
    img_size: [512, 512]
    tex_path:
    texture_optimization: True

    # SMPLX cam params
    dist: 2.4
    elev: 8.6
    azim: 2.1

    # # FLAME shape cam params
    # dist: 0.8
    # elev: 0.0
    # azim: 0.0

    # # FLAME expression cam params
    # dist: 0.5
    # elev: 0.0
    # azim: 0.0

    # SMAL cam params
    # dist: 3.8
    # elev: 20.0
    # azim: 0.0